# Generated by Django 3.1.3 on 2020-11-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='reasons',
            field=models.TextField(default='Annual Leave'),
        ),
    ]
