# Generated by Django 3.1.3 on 2020-11-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20201113_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='status',
            new_name='Approved',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='comments',
        ),
    ]
