# Generated by Django 3.1.3 on 2020-11-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20201113_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='Approved',
            field=models.BooleanField(default='Pending'),
        ),
    ]
