# Generated by Django 3.1.3 on 2020-11-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20201113_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='Approved',
        ),
    ]
