# Generated by Django 3.1.3 on 2020-11-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_remove_leave_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='Approved',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Denied')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
