# Generated by Django 3.1.3 on 2020-11-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leave_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='Approved',
            new_name='status',
        ),
    ]
