# Generated by Django 3.1.3 on 2020-11-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20201115_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='comments',
            field=models.TextField(default='under review'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
    ]
