# Generated by Django 3.1.3 on 2020-11-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201118_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
