# Generated by Django 3.1.3 on 2020-11-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_departmenthead_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmenthead',
            name='is_superuser',
        ),
    ]
