# Generated by Django 3.1.3 on 2020-11-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201113_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='id',
            new_name='role',
        ),
    ]
