# Generated by Django 3.1.3 on 2020-11-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201112_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
