# Generated by Django 3.1.3 on 2020-11-23 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201124_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='statuz',
            new_name='status',
        ),
    ]
