# Generated by Django 3.1.3 on 2020-11-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_auto_20201118_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='postal_address',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
