# Generated by Django 3.1.3 on 2020-11-18 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0005_auto_20201118_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_head',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='departments.department'),
        ),
    ]
